# Generated by Django 6.0.2 on 2026-03-15 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupe', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('Pasaporte', 'Pasaporte'), ('CE', 'Carné de Extranjería')], default='DNI', max_length=20)),
                ('document_num', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(choices=[('Lima', 'Lima'), ('Arequipa', 'Arequipa'), ('Cusco', 'Cusco'), ('Trujillo', 'Trujillo'), ('Piura', 'Piura'), ('Ica', 'Ica')], default='Lima', max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'collaborators',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.CharField(choices=[('L1', 'Superadmin'), ('L2', 'Scrum Master'), ('L3', 'Tech Lead'), ('L4', 'Líder'), ('L5', 'Developer')], max_length=2, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='WebCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'web_catalog',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CupeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_cupe', models.CharField(max_length=15)),
                ('new_cupe', models.CharField(max_length=15)),
                ('reason', models.CharField(choices=[('error_generacion', 'Error de generación'), ('reingreso', 'Reingreso'), ('correccion_admin', 'Corrección administrativa'), ('otro', 'Otro')], max_length=30)),
                ('observations', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupe_authorizations', to='clients.collaborator')),
            ],
            options={
                'db_table': 'cupe_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='collaborator',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collaborators', to='clients.role'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupe', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('Pasaporte', 'Pasaporte')], default='DNI', max_length=20)),
                ('document_num', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('plan', models.CharField(choices=[('alquiler', 'Alquiler'), ('venta', 'Venta')], default='alquiler', max_length=10)),
                ('initial_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_payment', models.DateField(blank=True, null=True)),
                ('domain_option', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('desarrollo', 'En desarrollo'), ('inactivo', 'Inactivo')], default='desarrollo', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('web_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.webcatalog')),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('web_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='clients.webcatalog')),
            ],
            options={
                'db_table': 'web_features',
                'ordering': ['name'],
                'unique_together': {('name', 'web_type')},
            },
        ),
    ]
