# Generated by Django 6.0.2 on 2026-03-15 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='web_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='clients.webcatalog'),
        ),
    ]
