# Generated by Django 6.0.2 on 2026-03-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_web_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='document_num',
            new_name='document_number',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='status',
        ),
        migrations.AddField(
            model_name='collaborator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
