# Generated by Django 6.0.2 on 2026-03-15 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_document_num_collaborator_document_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupelog',
            options={'ordering': ['-changed_at']},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='monthly_amount',
            new_name='base_price',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='next_payment',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='document_num',
            new_name='document_number',
        ),
        migrations.RenameField(
            model_name='cupelog',
            old_name='timestamp',
            new_name='changed_at',
        ),
        migrations.RenameField(
            model_name='webcatalog',
            old_name='monthly_price',
            new_name='base_price_rent',
        ),
        migrations.RenameField(
            model_name='webcatalog',
            old_name='sale_price',
            new_name='base_price_sale',
        ),
        migrations.AlterUniqueTogether(
            name='webfeature',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='client',
            name='domain_option',
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to='clients.collaborator'),
        ),
        migrations.AddField(
            model_name='client',
            name='domain_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='client',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_frequency',
            field=models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('anual', 'Anual')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cupelog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupe_changes', to='clients.collaborator'),
        ),
        migrations.AddField(
            model_name='cupelog',
            name='entity_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cupelog',
            name='entity_type',
            field=models.CharField(choices=[('client', 'Cliente'), ('collaborator', 'Colaborador')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webcatalog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='webfeature',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webfeature',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='document_type',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], default='DNI', max_length=10),
        ),
        migrations.AlterField(
            model_name='webfeature',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='webfeature',
            name='description',
        ),
        migrations.RemoveField(
            model_name='webfeature',
            name='web_type',
        ),
        migrations.CreateModel(
            name='ClientFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='clients.client')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_features', to='clients.webfeature')),
            ],
            options={
                'db_table': 'client_features',
                'unique_together': {('client', 'feature')},
            },
        ),
    ]
