# Generated by Django 6.0.2 on 2026-09-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupelog',
            name='reason',
            field=models.CharField(choices=[('error_generacion', 'Error de generación'), ('reingreso', 'Reingreso'), ('correccion_admin', 'Corrección administrativa'), ('correccion_administrativa', 'Corrección administrativa'), ('solicitud_cliente', 'Solicitud del cliente'), ('migracion_sistema', 'Migración del sistema'), ('otro', 'Otro')], max_length=30),
        ),
    ]
